name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Create .env file
      run: |
        echo "VITE_TMDB_API_KEY=${{ secrets.MY_SECRET_TOKEN }}" > .env

    - name: Install dependencies
      run: npm install

    - name: Build lint
      run: npm run lint

    - name: Run test:coverage
      run: npm run test:coverage
      continue-on-error: true

    - name: Build project
      run: npm run build

    - name: Copy coverage report to dist
      run: |
        mkdir -p dist/coverage
        cp -r coverage/lcov-report/* dist/coverage

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist